### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by atsyplenkov** [AntoniusGolly/cmgo#1]
Please, update the dependencies of your package. Now it's impossible to install this library because of the `spatstat` package. It has been updated to the 2.1-0 version, and some functions were depreciated. For example, I've got this error message:

> object 'dirichlet' is not exported by 'namespace:spatstat'

**Comment by AntoniusGolly** [comment]
This package needs major reviews. Have you been using the package before? Would you be interested in devloping it?

**Comment by atsyplenkov** [comment]
No, I haven't used it before. I'm not sure that it would be easy for me to dive in. However, I would like to contribute. You can write me an email on Gmail to discuss this further.

**Comment by AntoniusGolly** [comment]
I updated the imports from `spatstat` to `spatstat.geom`. They seem to have moved it in v2. For me it works now.
